server:
  port: 8888

spring:
  application:
    name: config-server
  security:
    user:
      name: root
      password: s3cr3t
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aliciaVillon/ms-admin-server-data.git
          clone-on-start: true
          default-label: master
          search-paths: {application}
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
